/*
 * AEOLUsrs API
 * Documentation of the A curated and standardized adverse drug event resource to accelerate drug safety research (AEOLUS) web query services. Learn more about the underlying dataset [HERE](https://www.nature.com/articles/sdata201626)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jmbanda@stanford.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContingencyTableApi
 */
@Ignore
public class ContingencyTableApiTest {

    private final ContingencyTableApi api = new ContingencyTableApi();

    
    /**
     * Uses drug and outcome codes in RxNorm and SNOMEDCT respectively to search AEOLUS and produce the corresponding contingency table.
     *
     * Makes drug/outcome coded query and returns two by two contingency table.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contingencyTableCodesTest() throws ApiException {
        String drugCode = null;
        String outcomeCode = null;
        api.contingencyTableCodes(drugCode, outcomeCode);

        // TODO: test validations
    }
    
    /**
     * Uses drug and outcome names in RxNorm and SNOMEDCT respectively to search AEOLUS and produce the corresponding contingency table.
     *
     * Makes drug/outcome coded query and returns two by two contingency table.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contingencyTableNamesTest() throws ApiException {
        String drugName = null;
        String outcomeName = null;
        api.contingencyTableNames(drugName, outcomeName);

        // TODO: test validations
    }
    
}
